apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Name of the deployment the HPA will scale
    name: deployment-name
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  # The HPA controller will keep the average utilization of the pods in the targeted deployment at 60%
  # Utilization is the ratio between the current usage of resource to the requested resources of the pod, the resource usages of all the containers are summed up
  # Resource requests MUST be set for this to work  
