apiVersion: autoscaling/v2beta2 
# Run `kubectl api-versions` to check if this API version is supported in your cluster
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-memory 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    # Name of the deployment the HPA will scale
    name: deployment-name 
  minReplicas: 5 
  maxReplicas: 20 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageValue: 10Mi 
        # The HPA controller will keep the average memory value of the pods in the targeted deployment at 10Mi
        # For this to work the memory usage has to decrease as the number of replicas increases